spring:
  datasource:
    url: jdbc:postgresql://smart-home-monolith2-postgresql-0:5432/smart_home
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
