spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/smart_home
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
  management:
    endpoints:
      health:
        probes:
          enabled: true
      web:
        exposure:
          include: health,info
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  port: 8080
logging:
  level:
    root: trace